# Generated by Django 5.0.7 on 2025-02-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='year',
            field=models.CharField(default=2000, max_length=4),
            preserve_default=False,
        ),
    ]
