# Generated by Django 5.0.7 on 2025-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_bookmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
