# Generated by Django 5.0.7 on 2025-02-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_alter_bookmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
