# Generated by Django 5.0.7 on 2025-02-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_alter_bookmodel_name_alter_bookmodel_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmodel',
            unique_together={('name', 'author', 'year')},
        ),
    ]
