# Generated by Django 5.0.7 on 2025-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_alter_bookmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
