# Generated by Django 5.0.7 on 2025-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0006_bookmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
